    ┌──────────────────────────────────────────────────────────────────────┐
    │                 • MobaXterm Personal Edition v25.0 •                 │
    │               (SSH client, X server and network tools)               │
    │                                                                      │
    │ ⮞ SSH session to root@f418b3c5b5c3.vps.myjino.ru                     │
    │   • Direct SSH      :  ✓                                             │
    │   • SSH compression :  ✓                                             │
    │   • SSH-browser     :  ✓                                             │
    │   • X11-forwarding  :  ✗  (disabled or not supported by server)      │
    │                                                                      │
    │ ⮞ For more info, ctrl+click on help or visit our website.            │
    └──────────────────────────────────────────────────────────────────────┘

Welcome to Ubuntu 22.04.5 LTS (GNU/Linux 5.2.0 x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro
Last login: Mon May 19 12:37:59 2025 from 90.156.255.117
root@f418b3c5b5c3:~# source venv/bin/activate
(venv) root@f418b3c5b5c3:~# venv\Scripts\activate
-bash: venvScriptsactivate: command not found
(venv) root@f418b3c5b5c3:~# pip install flask flask-cors gunicorn
Requirement already satisfied: flask in ./venv/lib/python3.10/site-packages (3.1.0)
Collecting flask-cors
  Downloading flask_cors-6.0.0-py3-none-any.whl.metadata (961 bytes)
Requirement already satisfied: gunicorn in ./venv/lib/python3.10/site-packages (23.0.0)
Requirement already satisfied: Werkzeug>=3.1 in ./venv/lib/python3.10/site-packages (from flask) (3.1.3)
Requirement already satisfied: Jinja2>=3.1.2 in ./venv/lib/python3.10/site-packages (from flask) (3.1.6)
Requirement already satisfied: itsdangerous>=2.2 in ./venv/lib/python3.10/site-packages (from flask) (2.2.0)
Requirement already satisfied: click>=8.1.3 in ./venv/lib/python3.10/site-packages (from flask) (8.1.8)
Requirement already satisfied: blinker>=1.9 in ./venv/lib/python3.10/site-packages (from flask) (1.9.0)
Requirement already satisfied: packaging in ./venv/lib/python3.10/site-packages (from gunicorn) (25.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from Jinja2>=3.1.2->flask) (3.0.2)
Downloading flask_cors-6.0.0-py3-none-any.whl (11 kB)
Installing collected packages: flask-cors
Successfully installed flask-cors-6.0.0
(venv) root@f418b3c5b5c3:~# gunicorn --bind 0.0.0.0:5000 main:app
[2025-05-19 12:44:26 +0000] [1104837] [INFO] Starting gunicorn 23.0.0
[2025-05-19 12:44:26 +0000] [1104837] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-05-19 12:44:26 +0000] [1104837] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2025-05-19 12:44:27 +0000] [1104837] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-05-19 12:44:27 +0000] [1104837] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2025-05-19 12:44:28 +0000] [1104837] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-05-19 12:44:28 +0000] [1104837] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2025-05-19 12:44:29 +0000] [1104837] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-05-19 12:44:29 +0000] [1104837] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2025-05-19 12:44:30 +0000] [1104837] [ERROR] Connection in use: ('0.0.0.0', 5000)
[2025-05-19 12:44:30 +0000] [1104837] [ERROR] connection to ('0.0.0.0', 5000) failed: [Errno 98] Address already in use
[2025-05-19 12:44:31 +0000] [1104837] [ERROR] Can't connect to ('0.0.0.0', 5000)
(venv) root@f418b3c5b5c3:~# curl ifconfig.me
(venv) root@f418b3c5b5c3:~# nano /etc/nginx/sites-available/marketingmaster.confgmaster.conf
(venv) root@f418b3c5b5c3:~# ln -sf /etc/nginx/sites-available/marketingmaster.conf /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl restart nginx
nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/rucoderweb.website/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/rucoderweb.website/fullchain.pem, r) error:10000080:BIO routines::no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
(venv) root@f418b3c5b5c3:~# ps aux | grep gunicorn
root     1102597  0.0  1.4  31160 22144 ?        Ss   12:39   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 127.0.0.1:5001 main:app
root     1102598  0.1  6.2 190368 97660 ?        S    12:39   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 127.0.0.1:5001 main:app
root     1102599  0.1  6.2 190368 97660 ?        S    12:39   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 127.0.0.1:5001 main:app
root     1102602  0.1  6.2 190364 97656 ?        S    12:39   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 127.0.0.1:5001 main:app
root     1104196  0.0  1.4  32176 22248 ?        S    12:43   0:00 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 main:app
root     1104607  0.2  6.6 214752 105284 ?       S    12:43   0:01 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 main:app
root     1104608  0.2  6.6 214752 105284 ?       S    12:43   0:01 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 main:app
root     1104609  0.2  6.6 214752 105288 ?       S    12:43   0:01 /usr/bin/python3 /usr/local/bin/gunicorn --workers 3 --bind 0.0.0.0:5000 main:app
root     1107566  0.0  0.1   3588  1644 pts/0    S+   12:50   0:00 grep --color=auto gunicorn
(venv) root@f418b3c5b5c3:~# cd /root/MarketingMaster
gunicorn --bind 127.0.0.1:5001 main:app
[2025-05-19 12:50:26 +0000] [1107608] [INFO] Starting gunicorn 23.0.0
[2025-05-19 12:50:26 +0000] [1107608] [ERROR] Connection in use: ('127.0.0.1', 5001)
[2025-05-19 12:50:26 +0000] [1107608] [ERROR] connection to ('127.0.0.1', 5001) failed: [Errno 98] Address already in use
[2025-05-19 12:50:27 +0000] [1107608] [ERROR] Connection in use: ('127.0.0.1', 5001)
[2025-05-19 12:50:27 +0000] [1107608] [ERROR] connection to ('127.0.0.1', 5001) failed: [Errno 98] Address already in use
[2025-05-19 12:50:28 +0000] [1107608] [ERROR] Connection in use: ('127.0.0.1', 5001)
[2025-05-19 12:50:28 +0000] [1107608] [ERROR] connection to ('127.0.0.1', 5001) failed: [Errno 98] Address already in use
[2025-05-19 12:50:29 +0000] [1107608] [ERROR] Connection in use: ('127.0.0.1', 5001)
[2025-05-19 12:50:29 +0000] [1107608] [ERROR] connection to ('127.0.0.1', 5001) failed: [Errno 98] Address already in use
[2025-05-19 12:50:30 +0000] [1107608] [ERROR] Connection in use: ('127.0.0.1', 5001)
[2025-05-19 12:50:30 +0000] [1107608] [ERROR] connection to ('127.0.0.1', 5001) failed: [Errno 98] Address already in use
[2025-05-19 12:50:31 +0000] [1107608] [ERROR] Can't connect to ('127.0.0.1', 5001)
(venv) root@f418b3c5b5c3:~/MarketingMaster# curl -H "Host: marketingmaster.space" http://127.0.0.1
curl: (7) Failed to connect to 127.0.0.1 port 80 after 0 ms: Connection refused
(venv) root@f418b3c5b5c3:~/MarketingMaster# apt install certbot python3-certbot-nginx -y
certbot --nginx -d marketingmaster.space -d www.marketingmaster.space
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
certbot is already the newest version (1.21.0-1build1).
python3-certbot-nginx is already the newest version (1.21.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] cannot load certificate "/etc/letsencrypt/live/rucoderweb.website/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:calling fopen(/etc/letsencrypt/live/rucoderweb.website/fullchain.pem, r) error:10000080:BIO routines::no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed

The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] cannot load certificate "/etc/letsencrypt/live/rucoderweb.website/fullchain.pem": BIO_new_file() failed (SSL: error:80000002:system library::No such file or directory:# Активируем конфигурацию nginx ln -sf /etc/nginx/sites-available/multi_domains.conf /etc/nginx/sites-enabled/ rm -f /etc/nginx/sites-enabled/default nginx -t && systemctl restart nginx # Перезапускаем systemd и службы systemctl daemon-reload systemctl enable marketingmaster telegramwebapp systemctl restart marketingmaster telegramwebappctl restart marketingmaster telegramwebapp systemctl enable market
(venv) root@f418b3c5b5c3:~/MarketingMaster# /etc/nginx/sites-available/multi_domains.conf
-bash: /etc/nginx/sites-available/multi_domains.conf: Permission denied
(venv) root@f418b3c5b5c3:~/MarketingMaster#
